name: Notificar Discord

on:
  issues:
    types: [opened, edited, closed, reopened, assigned]
  pull_request:
    types: [opened, edited, closed, reopened, ready_for_review]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Montar mensagem
        id: msg
        run: |
          EVENT="${{ github.event_name }}"
          ACT="${{ github.event.action }}"
          REPO="${{ github.repository }}"
          ACTOR="${{ github.actor }}"
          if [ "$EVENT" = "issues" ]; then
            NUM="${{ github.event.issue.number }}"
            TITLE="${{ github.event.issue.title }}"
            URL="${{ github.event.issue.html_url }}"
            echo "content=📝 Issue #$NUM *$TITLE* foi **$ACT** por **$ACTOR** — $URL" >> $GITHUB_OUTPUT
          else
            NUM="${{ github.event.pull_request.number }}"
            TITLE="${{ github.event.pull_request.title }}"
            URL="${{ github.event.pull_request.html_url }}"
            echo "content=🔀 PR #$NUM *$TITLE* foi **$ACT** por **$ACTOR** — $URL" >> $GITHUB_OUTPUT
          fi
      - name: Enviar para Discord
        run: |
          jq -n --arg content "${{ steps.msg.outputs.content }}" '{content: $content}' \
          | curl -H "Content-Type: application/json" -X POST -d @- "$DISCORD_WEBHOOK_URL"
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
